import React, { useState, useEffect } from 'react';
import './App.css';
import QRCode from 'react-qr-code';


function getQueryParams() {
  const params = new URLSearchParams(window.location.search);
  return {
    partner: params.get('partner') || 'Unknown Partner',
    scope: params.get('scope') ? params.get('scope').split(',') : [],
    purpose: params.get('purpose') || '',
    redirectUri: params.get('redirect_uri') || '',
  };
}

function App() {
  const [status, setStatus] = useState('Waiting for consent...');
  const params = getQueryParams();
  const consentSessionId = 'abc123xyz'; // In real flow, this would be generated by backend
  const qrLink = `bankapp://consent?session_id=${consentSessionId}`;

  // Simulate polling for consent status

  useEffect(() => {
    const timer = setTimeout(() => {
      setStatus('Consent Approved'); // Change to 'Consent Rejected' to simulate rejection
    }, 10000); // 10 seconds for demo
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    if ((status === 'Consent Approved' || status === 'Consent Rejected') && params.redirectUri) {
      setTimeout(() => {
        window.location.href = `${params.redirectUri}?status=${encodeURIComponent(status)}`;
      }, 2000); // 2 seconds to show status before redirect
    }
  }, [status, params.redirectUri]);

  return (
    <div className="consent-container">
      <header className="consent-header">
        <img src="/bank-logo.png" alt="Summit Trust Bank Logo" className="bank-logo" />
        <h1>Summit Trust Bank Consent</h1>
      </header>
      <main className="consent-main">
        <h2>Partner: {params.partner}</h2>
        <p><strong>Requested Info:</strong> {params.scope.join(', ')}</p>
        <p><strong>Purpose:</strong> {params.purpose}</p>
        <div className="qr-section">
          <p>Scan this QR code with your Summit Trust Bank mobile app to continue.</p>
          <div className="qr-code">
            <QRCode value={qrLink} size={180} />
          </div>
          <div className="qr-warning" style={{marginTop: '1.5rem', color: '#b71c1c', fontWeight: 'bold'}}>
            <span role="img" aria-label="warning">⚠️</span> Please do not close, refresh, or use the back button on this page until the consent process is complete.
          </div>
        </div>
        <div className="status-section">
          <p>Status: {status}</p>
        </div>
      </main>
      <footer className="consent-footer">
        <small>&copy; {new Date().getFullYear()} Summit Trust Bank</small>
      </footer>
    </div>
  );
}

export default App
